image: "chef/chefworkstation"

services:
  - docker:dind

# Shared variables which we'll attach to jobs
.shared_variables: &shared_variables
  CHEF_LICENSE: accept

before_script:
  - echo $(admin-pem) | base64 -d > ~/.chef/admin.pem
  - echo $(knife-rb) | base64 -d > ~/.chef/knife.rb

stages:
  - test
  - build
  - publish
  - promote_stg
  - promote_prod

cookstyle:
  stage: test
  script:
    - chef exec cookstyle .
  variables:
    <<: *shared_variables

chefspec:
  stage: test
  script:
    - chef exec rspec .
  variables:
    <<: *shared_variables

test_kitchen:
  stage: test
  script:
    - chef exec kitchen test
  variables:
    <<: *shared_variables

create_artifact:
  stage: build
  artifacts:
    paths:
      - Policyfile.lock.json
  script:
    - chef install
  variables:
    <<: *shared_variables

publish_artifact:
  stage: publish
  artifacts:
    paths:
      - Policyfile.lock.json
  script:
    - chef push dev
  variables:
    <<: *shared_variables

promote_stg:
  stage: promote_stg
  artifacts:
    paths:
      - Policyfile.lock.json
  script:
    - chef push stg
  variables:
    <<: *shared_variables
  when: manual

promote_prod:
  stage: promote_prod
  artifacts:
    paths:
      - Policyfile.lock.json
  script:
    - chef push prod
  variables:
    <<: *shared_variables
  when: manual
