image: "chef/chefworkstation"

services:
  - docker:dind

# Shared variables which we'll attach to jobs
.shared_variables: &shared_variables
  HAB_LICENSE: accept
  CHEF_LICENSE: accept

before_script:
  - apt-get update
  - apt-get install -y curl wget
  - echo $sig | base64 -d > /hab/cache/keys/origin-20191217002439.pub
  - echo $key | base64 -d > /hab/cache/keys/origin-20191217002439.sig.key
  - mkdir - p /hab/etc
  - echo $cli | base64 -d > /hab/etc/cli.toml

stages:
  - test
  - build
  - publish
  - promote_stg
  - promote_prod

cookstyle:
  stage: test
  script:
    - chef exec cookstyle .
  variables:
    <<: *shared_variables

chefspec:
  stage: test
  script:
    - chef exec rspec .
  variables:
    <<: *shared_variables

kitchen_test:
  stage: test
  script:
    - chef exec kitchen test
  variables:
    <<: *shared_variables

create_artifact:
  stage: build
  artifacts:
    paths:
      - results/
  script:
    - hab pkg build habitat/.
  variables:
    <<: *shared_variables

publish_artifact:
  stage: publish
  artifacts:
    paths:
      - results/
  script:
    - source results/last_build.env
    - hab pkg upload results/$pkg_artifact
  variables:
    <<: *shared_variables

promote_stg:
  stage: promote_stg
  artifacts:
    paths:
      - results/
  script:
    - source results/last_build.env
    - hab pkg promote $pkg_ident stg
  variables:
    <<: *shared_variables
  when: manual

promote_prod:
  stage: promote_prod
  artifacts:
    paths:
      - results/
  script:
    - source results/last_build.env
    - hab pkg promote $pkg_ident prod
  variables:
    <<: *shared_variables
  when: manual
